/*
Pattern Matcher Submissions: 294   Accuracy: 48.29%   Max. Score: 100

Given a string S and a pattern P, you need to find if S can be generated by using P one or more times.

Input:
For each testcase, first line of input contains number of testcases T. For each testcase, there will be two lines of input, first of which contains the pattern P and the next line contains string S.

Output:
For each testcase, print "1"(without quotes), if possible, else print "0"(without quotes).

Constraints:
1 <= T <= 100
a <= S[i] <= z

Example:
Input:
2
abba
abbaabb
abba
abba

Output:
0
1
*/


import java.util.*;
import java.lang.*;
import java.io.*;

class GFG {
    
    static int checkPattern(String str, String ptr) {
        int i=0;
        String sb;
        int plen = ptr.length();
        int slen = str.length();
        while (i < str.length() ) {
            if((i+plen-1) <= slen-1 )
                sb = str.substring(i, i+plen );
            else 
                sb = str.substring(i, slen-1);
            if(sb.equals(ptr)) {
                i = i+plen;
            } else {
                return 0;
            }
        }
        return 1;
    }
    
	public static void main (String[] args) throws IOException {
		int t;
		BufferedReader bf = new BufferedReader(new InputStreamReader(
		        System.in));
		t = Integer.parseInt(bf.readLine());
		while (t>0) {
		    t--;
		    String ptr = bf.readLine();
		    String str = bf.readLine();
		    
		    System.out.println(checkPattern(str, ptr) );
		    }
	}
}